import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar-background)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        btn: {
          primary: {
            DEFAULT: "var(--btn-primary-bg)",
            foreground: "var(--btn-primary-fg)",
            hover: "var(--btn-primary-hover)",
          },
          secondary: {
            DEFAULT: "var(--btn-secondary-bg)",
            foreground: "var(--btn-secondary-fg)",
            hover: "var(--btn-secondary-hover)",
          },
          danger: {
            DEFAULT: "var(--btn-danger-bg)",
            foreground: "var(--btn-danger-fg)",
            hover: "var(--btn-danger-hover)",
          },
          success: {
            DEFAULT: "var(--btn-success-bg)",
            foreground: "var(--btn-success-fg)",
            hover: "var(--btn-success-hover)",
          },
          ghost: {
            DEFAULT: "var(--btn-ghost-bg)",
            foreground: "var(--btn-ghost-fg)",
            hover: "var(--btn-ghost-hover)",
          },
          outline: {
            DEFAULT: "var(--btn-outline-bg)",
            foreground: "var(--btn-outline-fg)",
            border: "var(--btn-outline-border)",
          },
        },
        nav: {
          DEFAULT: "var(--nav-bg)",
          foreground: "var(--nav-fg)",
          hover: "var(--nav-hover)",
          active: "var(--nav-active)",
          "active-foreground": "var(--nav-active-fg)",
          border: "var(--nav-border)",
          link: "var(--nav-link)",
          "link-hover": "var(--nav-link-hover)",
        },
        inputField: {
          DEFAULT: "var(--input-bg)",
          foreground: "var(--input-fg)",
          border: "var(--input-border)",
          focus: "var(--input-focus)",
          placeholder: "var(--input-placeholder)",
        },
        success: {
          DEFAULT: "var(--success)",
          foreground: "var(--success-foreground)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          foreground: "var(--warning-foreground)",
        },
        table: {
          header: "var(--table-header-bg)",
          "header-foreground": "var(--table-header-fg)",
          row: "var(--table-row-bg)",
          "row-alt": "var(--table-row-alt-bg)",
          "row-hover": "var(--table-row-hover-bg)",
          border: "var(--table-cell-border)",
        },
        toast: {
          DEFAULT: "var(--toast-bg)",
          foreground: "var(--toast-fg)",
          border: "var(--toast-border)",
          success: "var(--toast-success-bg)",
          error: "var(--toast-error-bg)",
        },
        hero: {
          bg: "var(--hero-bg)",
          "bg-gradient-from": "var(--hero-bg-gradient-from)",
          "bg-gradient-via": "var(--hero-bg-gradient-via)",
          "bg-gradient-to": "var(--hero-bg-gradient-to)",
          "headline-from": "var(--hero-headline-from)",
          "headline-via": "var(--hero-headline-via)",
          "headline-to": "var(--hero-headline-to)",
          "cta-primary": "var(--hero-cta-primary-bg)",
          "cta-primary-fg": "var(--hero-cta-primary-fg)",
          "cta-primary-hover": "var(--hero-cta-primary-hover)",
          "cta-secondary": "var(--hero-cta-secondary-bg)",
          "cta-secondary-fg": "var(--hero-cta-secondary-fg)",
          "cta-secondary-hover": "var(--hero-cta-secondary-hover)",
          glow: "var(--hero-glow)",
          "glow-secondary": "var(--hero-glow-secondary)",
        },
        badge: {
          DEFAULT: "var(--badge-bg)",
          foreground: "var(--badge-fg)",
          hover: "var(--badge-hover-bg)",
          secondary: "var(--badge-secondary-bg)",
          "secondary-foreground": "var(--badge-secondary-fg)",
          outline: "var(--badge-outline-bg)",
          "outline-foreground": "var(--badge-outline-fg)",
          "outline-border": "var(--badge-outline-border)",
          success: "var(--badge-success-bg, var(--success))",
          "success-foreground": "var(--badge-success-fg, var(--success-foreground))",
          warning: "var(--badge-warning-bg, var(--warning))",
          "warning-foreground": "var(--badge-warning-fg, var(--warning-foreground))",
          danger: "var(--badge-danger-bg, var(--destructive))",
          "danger-foreground": "var(--badge-danger-fg, var(--destructive-foreground))",
          info: "var(--badge-info-bg, var(--info))",
          "info-foreground": "var(--badge-info-fg, var(--info-foreground))",
        },
        tab: {
          DEFAULT: "var(--tab-bg)",
          foreground: "var(--tab-fg)",
          hover: "var(--tab-hover-bg)",
          "hover-foreground": "var(--tab-hover-fg)",
          active: "var(--tab-active-bg)",
          "active-foreground": "var(--tab-active-fg)",
          "active-hover": "var(--tab-active-hover-bg)",
          "focus-ring": "var(--tab-focus-ring)",
          "disabled-foreground": "var(--tab-disabled-fg)",
          border: "var(--tab-border)",
          indicator: "var(--tab-indicator)",
        },
        modal: {
          DEFAULT: "var(--modal-bg)",
          foreground: "var(--modal-fg)",
          border: "var(--modal-border)",
          overlay: "var(--modal-overlay)",
        },
        skeleton: {
          DEFAULT: "var(--skeleton-bg)",
          highlight: "var(--skeleton-highlight)",
        },
        glow: {
          DEFAULT: "var(--game-glow)",
          effect: "var(--effect-glow)",
          primary: "var(--game-primary)",
          gold: "var(--game-gold)",
          "gold-light": "var(--game-gold-light)",
          success: "var(--game-success)",
          xp: "var(--game-xp)",
          particle: "var(--game-particle)",
        },
        surface: {
          base: "var(--surface-base)",
          raised: "var(--surface-raised)",
          overlay: "var(--surface-overlay)",
          inverse: "var(--surface-inverse)",
        },
        "accent-tier": {
          "primary-strong": "var(--accent-primary-strong)",
          "secondary-strong": "var(--accent-secondary-strong)",
          tertiary: "var(--accent-tertiary)",
          "tertiary-strong": "var(--accent-tertiary-strong)",
        },
        fg: {
          strong: "var(--fg-strong)",
          default: "var(--fg-default)",
          muted: "var(--fg-muted)",
        },
        body: {
          base: "var(--body-base)",
          muted: "var(--body-muted)",
        },
        dropdown: {
          fg: "var(--dropdown-fg)",
          "item-hover-foreground": "var(--dropdown-item-hover-fg)",
          "item-active-foreground": "var(--dropdown-item-active-fg)",
        },
        select: {
          fg: "var(--select-fg)",
        },
        cta: {
          fg: "var(--cta-fg)",
        },
        link: {
          fg: "var(--link-fg)",
          "hover-foreground": "var(--link-hover-fg)",
        },

        section: {
          heading: "var(--section-heading)",
          subheading: "var(--section-subheading)",
        },
        footer: {
          heading: "var(--footer-heading)",
          fg: "var(--footer-fg)",
          link: "var(--footer-link)",
        },
        glass: {
          "card-title": "var(--glass-card-title)",
          "card-text": "var(--glass-card-text)",
        },
        feature: {
          "card-title": "var(--feature-card-title)",
          "card-body": "var(--feature-card-body)",
          "card-icon-fg": "var(--feature-card-icon-fg)",
        },
        "state-halo": {
          info: "var(--state-halo-info)",
          success: "var(--state-halo-success)",
          warning: "var(--state-halo-warning)",
          danger: "var(--state-halo-danger)",
          active: "var(--state-halo-active)",
          paired: "var(--state-halo-paired)",
        },
        "game-surface": {
          base: "var(--game-surface-base)",
          highlight: "var(--game-surface-highlight)",
          muted: "var(--game-surface-muted)",
          success: "var(--game-surface-success)",
          error: "var(--game-surface-error)",
        },
        stats: {
          surface: "var(--stats-surface-base)",
          "surface-emphasis": "var(--stats-surface-emphasis)",
          "text-muted": "var(--stats-text-muted)",
          "icon-accent": "var(--stats-icon-accent)",
          number: "var(--stats-number)",
          label: "var(--stats-label)",
        },
        alert: {
          info: {
            DEFAULT: "var(--alert-info-bg)",
            foreground: "var(--alert-info-fg)",
            border: "var(--alert-info-border)",
            icon: "var(--alert-info-icon)",
          },
          success: {
            DEFAULT: "var(--alert-success-bg)",
            foreground: "var(--alert-success-fg)",
            border: "var(--alert-success-border)",
            icon: "var(--alert-success-icon)",
          },
          warning: {
            DEFAULT: "var(--alert-warning-bg)",
            foreground: "var(--alert-warning-fg)",
            border: "var(--alert-warning-border)",
            icon: "var(--alert-warning-icon)",
          },
          danger: {
            DEFAULT: "var(--alert-danger-bg)",
            foreground: "var(--alert-danger-fg)",
            border: "var(--alert-danger-border)",
            icon: "var(--alert-danger-icon)",
          },
        },
        accordion: {
          DEFAULT: "var(--accordion-bg)",
          foreground: "var(--accordion-fg)",
          border: "var(--accordion-border)",
          "trigger-hover": "var(--accordion-trigger-hover-bg)",
          content: "var(--accordion-content-bg)",
          icon: "var(--accordion-icon)",
          "icon-hover": "var(--accordion-icon-hover)",
        },
        progress: {
          bar: "var(--progress-bar-bg)",
          fill: "var(--progress-bar-fill)",
        },
      },
      boxShadow: {
        card: "var(--card-shadow)",
        "card-hover": "var(--card-hover-shadow)",
        form: "var(--auth-form-shadow)",
        "course-card": "var(--course-card-hover-shadow)",
        elevated: "var(--shadow-elevated)",
        dialog: "var(--shadow-dialog)",
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(to right, var(--gradient-primary-from), var(--gradient-primary-to))",
        "gradient-accent": "linear-gradient(to right, var(--gradient-accent-from), var(--gradient-accent-to))",
        "cta-gradient": "linear-gradient(to right, var(--cta-gradient-from), var(--cta-gradient-to))",
        "hero-gradient": "linear-gradient(to bottom right, var(--hero-bg-gradient-from), var(--hero-bg-gradient-via), var(--hero-bg-gradient-to))",
        "hero-headline": "linear-gradient(to right, var(--hero-headline-from), var(--hero-headline-via), var(--hero-headline-to))",
        "hero-cta": "linear-gradient(to right, var(--hero-cta-primary-bg), var(--hero-cta-primary-hover))",
      },
      
      fontFamily: {
        sans: ["Inter", "var(--font-sans)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
        pan: {
          "0%": { transform: "translate(0, 0)" },
          "100%": { transform: "translate(-200px, -100px)" },
        },
        fadeInUp: {
          to: {
            opacity: "1",
            transform: "translateY(0)",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        pan: "pan 60s linear infinite",
        "pan-reverse": "pan 80s linear infinite reverse",
        "fade-in-up": "fadeInUp 1.5s ease-out forwards",
        "fade-in-up-delay": "fadeInUp 1.5s ease-out 0.5s forwards",
        "fade-in-up-delay-2": "fadeInUp 1.5s ease-out 1s forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
