import type { InsertPowerUpCatalog, InsertCosmeticCatalog, InsertGammaImageStyle } from "@shared/schema";

export const CATALOG_VERSION = 1;

export const POWER_UP_DEFINITIONS: Array<Omit<InsertPowerUpCatalog, 'createdAt'> & { id: string }> = [
  {
    id: "pu-001-xpboost-10min-0000-000000000001",
    name: "XP Boost (10 min)",
    description: "Double XP for 10 minutes",
    type: "xp_boost",
    effect: { multiplier: 2, duration: 600 },
    coinCost: 100,
    tier: "common",
    isActive: true,
  },
  {
    id: "pu-002-xpboost-30min-0000-000000000002",
    name: "XP Boost (30 min)",
    description: "Double XP for 30 minutes",
    type: "xp_boost",
    effect: { multiplier: 2, duration: 1800 },
    coinCost: 250,
    tier: "rare",
    isActive: true,
  },
  {
    id: "pu-003-triplexp-5min-0000-000000000003",
    name: "Triple XP (5 min)",
    description: "Triple XP for 5 minutes",
    type: "xp_boost",
    effect: { multiplier: 3, duration: 300 },
    coinCost: 300,
    tier: "epic",
    isActive: true,
  },
  {
    id: "pu-004-timeext-30sec-0000-000000000004",
    name: "Time Extension",
    description: "+30 seconds for each question",
    type: "time_extension",
    effect: { bonus: 30, duration: 600 },
    coinCost: 200,
    tier: "rare",
    isActive: true,
  },
];

export const COSMETIC_DEFINITIONS: Array<Omit<InsertCosmeticCatalog, 'createdAt'> & { id: string }> = [
  {
    id: "cos-001-redglow-ring-00000-000000000001",
    name: "Red Glow",
    description: "Red glow effect around avatar",
    type: "avatar_ring",
    effect: { color: "#ff0000", animation: "glow" },
    coinCost: 500,
    tier: "common",
    isActive: true,
  },
  {
    id: "cos-002-blueglow-ring-0000-000000000002",
    name: "Blue Glow",
    description: "Blue glow effect around avatar",
    type: "avatar_ring",
    effect: { color: "#0066ff", animation: "glow" },
    coinCost: 500,
    tier: "common",
    isActive: true,
  },
  {
    id: "cos-003-goldglow-ring-0000-000000000003",
    name: "Golden Glow",
    description: "Golden glow effect around avatar",
    type: "avatar_ring",
    effect: { color: "#ffd700", animation: "glow" },
    coinCost: 1000,
    tier: "rare",
    isActive: true,
  },
  {
    id: "cos-004-firering-ring-0000-000000000004",
    name: "Fire Ring",
    description: "Ring of fire around avatar",
    type: "avatar_ring",
    effect: { color: "#ff4500", animation: "fire" },
    coinCost: 2000,
    tier: "epic",
    isActive: true,
  },
  {
    id: "cos-005-lightning-ring-000-000000000005",
    name: "Lightning Aura",
    description: "Electric lightning aura",
    type: "avatar_ring",
    effect: { color: "#00ffff", animation: "lightning" },
    coinCost: 3000,
    tier: "legendary",
    isActive: true,
  },
  {
    id: "cos-006-diamond-frame-0000-000000000006",
    name: "Diamond Frame",
    description: "Diamond-shaped avatar frame",
    type: "avatar_frame",
    effect: { shape: "diamond", color: "#ffffff" },
    coinCost: 1500,
    tier: "rare",
    isActive: true,
  },
  {
    id: "cos-007-crownfr-frame-000-000000000007",
    name: "Crown Frame",
    description: "Crown-shaped avatar frame",
    type: "avatar_frame",
    effect: { shape: "crown", color: "#ffd700" },
    coinCost: 2500,
    tier: "epic",
    isActive: true,
  },
  {
    id: "cos-008-purple-name-00000-000000000008",
    name: "Purple Name",
    description: "Purple colored username",
    type: "name_color",
    effect: { color: "#9b59b6" },
    coinCost: 800,
    tier: "common",
    isActive: true,
  },
  {
    id: "cos-009-golden-name-00000-000000000009",
    name: "Golden Name",
    description: "Golden colored username",
    type: "name_color",
    effect: { color: "#ffd700" },
    coinCost: 1200,
    tier: "rare",
    isActive: true,
  },
  {
    id: "cos-010-rainbow-name-0000-000000000010",
    name: "Rainbow Name",
    description: "Rainbow gradient username",
    type: "name_color",
    effect: { color: "rainbow", animation: "gradient" },
    coinCost: 2000,
    tier: "epic",
    isActive: true,
  },
];

export const GAMMA_IMAGE_STYLE_DEFINITIONS: Omit<InsertGammaImageStyle, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    styleKey: "photorealistic",
    displayName: "Photorealistic",
    description: "High-quality realistic images",
    thumbnailUrl: "/api/public-objects/gamma/image-styles/photorealistic.jpeg",
    recommendedUseCases: ["Professional presentations", "Business reports", "Academic content"],
    source: "manual",
    isActive: true,
    weight: 100,
    lastSyncedAt: null,
  },
  {
    styleKey: "illustrated",
    displayName: "Illustrated",
    description: "Hand-drawn, artistic illustrations",
    thumbnailUrl: "/api/public-objects/gamma/image-styles/illustrated.jpeg",
    recommendedUseCases: ["Creative projects", "Storytelling", "Educational content"],
    source: "manual",
    isActive: true,
    weight: 80,
    lastSyncedAt: null,
  },
  {
    styleKey: "minimal",
    displayName: "Minimal",
    description: "Clean, simple, minimalist design",
    thumbnailUrl: "/api/public-objects/gamma/image-styles/minimal.jpeg",
    recommendedUseCases: ["Modern presentations", "Startup pitches", "Tech content"],
    source: "manual",
    isActive: true,
    weight: 60,
    lastSyncedAt: null,
  },
  {
    styleKey: "corporate",
    displayName: "Corporate",
    description: "Professional business-style images",
    thumbnailUrl: "/api/public-objects/gamma/image-styles/corporate.jpeg",
    recommendedUseCases: ["Business meetings", "Corporate training", "Financial reports"],
    source: "manual",
    isActive: true,
    weight: 40,
    lastSyncedAt: null,
  },
  {
    styleKey: "playful",
    displayName: "Playful",
    description: "Fun and creative cartoon-style images",
    thumbnailUrl: "/api/public-objects/gamma/image-styles/playful.jpeg",
    recommendedUseCases: ["Children's content", "Creative projects", "Casual presentations"],
    source: "manual",
    isActive: true,
    weight: 20,
    lastSyncedAt: null,
  },
];
