-- Auto-generated from DEV runtime DB diff since last successful build
-- Scope: cloud
-- Previous schema hash: 01172ffc3b9397105a21cebc14891a4fabe432a55466ad98fafd3f712ca2b77d
-- Current schema hash: f7c9e12e50ce001a061e4916baa459f91c17984da3462e3aec46b15d02dd844c
-- Generated at: 2026-04-07T12:39:19.288Z
DO $$ BEGIN ALTER TABLE IF EXISTS "courseLessons" ADD CONSTRAINT "courseLessons_courseId_courses_id_fk" FOREIGN KEY ("courseId") REFERENCES courses(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseLessons" ADD CONSTRAINT "courseLessons_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseLessons" ADD CONSTRAINT "UNQ_course_lesson" UNIQUE ("courseId", "lessonId"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courses" ADD CONSTRAINT "courses_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "currencyConversionRates" ADD CONSTRAINT "currencyConversionRates_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "enterpriseCustomers" ADD CONSTRAINT "enterprise_customers_email_unique" UNIQUE (email); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "enterpriseCustomers" ADD CONSTRAINT "enterprise_customers_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "enterpriseLicenseKeys" ADD CONSTRAINT "enterprise_license_keys_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "enterpriseLicenseRequests" ADD CONSTRAINT "enterprise_license_requests_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "enterpriseSystems" ADD CONSTRAINT "enterprise_systems_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizations" ADD CONSTRAINT "organizations_inviteCode_unique" UNIQUE ("inviteCode"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizations" ADD CONSTRAINT "organizations_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformConfiguration" ADD CONSTRAINT "platformConfiguration_key_unique" UNIQUE (key); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformConfiguration" ADD CONSTRAINT "platformConfiguration_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformPricing" ADD CONSTRAINT "platformPricing_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizCreditPricing" ADD CONSTRAINT "quizCreditPricing_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizCreditPricing" ADD CONSTRAINT "UNQ_quiz_pricing_org_tier" UNIQUE ("organizationId", "questionTier"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "supportedLanguages" ADD CONSTRAINT "supportedLanguages_pkey" PRIMARY KEY (code); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "systemSettings" ADD CONSTRAINT "systemSettings_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "systemSettings" ADD CONSTRAINT "systemSettings_settingKey_key" UNIQUE ("settingKey"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "systemSettings" ADD CONSTRAINT "systemSettings_settingKey_unique" UNIQUE ("settingKey"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "userOrganizationRoles" ADD CONSTRAINT "userOrganizationRoles_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "users" ADD CONSTRAINT "users_email_unique" UNIQUE (email); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "users" ADD CONSTRAINT "users_gamerName_unique" UNIQUE ("gamerName"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS branding_themes_organization_id_unique ON public."brandingThemes" USING btree ("organizationId");
CREATE UNIQUE INDEX IF NOT EXISTS branding_themes_platform_singleton_idx ON public."brandingThemes" USING btree ((1)) WHERE ("organizationId" IS NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "build_versions_versionNumber_unique" ON public."buildVersions" USING btree ("versionNumber");
CREATE INDEX IF NOT EXISTS "IDX_build_versions_active" ON public."buildVersions" USING btree ("isActive");
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_build_versions_version" ON public."buildVersions" USING btree ("versionNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "courseLessons_pkey" ON public."courseLessons" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "UNQ_course_lesson" ON public."courseLessons" USING btree ("courseId", "lessonId");
CREATE UNIQUE INDEX IF NOT EXISTS courses_pkey ON public.courses USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "currencyConversionRates_pkey" ON public."currencyConversionRates" USING btree (id);
CREATE INDEX IF NOT EXISTS "IDX_enterprise_agreement_templates_active" ON public."enterpriseAgreementTemplates" USING btree ("isActive");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_agreement_templates_type" ON public."enterpriseAgreementTemplates" USING btree ("templateType");
CREATE UNIQUE INDEX IF NOT EXISTS enterprise_customers_email_unique ON public."enterpriseCustomers" USING btree (email);
CREATE UNIQUE INDEX IF NOT EXISTS enterprise_customers_pkey ON public."enterpriseCustomers" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_enterprise_customers_email" ON public."enterpriseCustomers" USING btree (email);
CREATE INDEX IF NOT EXISTS "IDX_enterprise_customers_parent" ON public."enterpriseCustomers" USING btree ("parentEnterpriseId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_documents_customer" ON public."enterpriseDocuments" USING btree ("enterpriseCustomerId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_documents_type" ON public."enterpriseDocuments" USING btree ("documentType");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_keyring_active" ON public."enterpriseKeyring" USING btree ("enterpriseCustomerId", "isActive");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_keyring_customer" ON public."enterpriseKeyring" USING btree ("enterpriseCustomerId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_keyring_purpose" ON public."enterpriseKeyring" USING btree ("enterpriseCustomerId", purpose);
CREATE UNIQUE INDEX IF NOT EXISTS enterprise_license_keys_pkey ON public."enterpriseLicenseKeys" USING btree (id);
CREATE INDEX IF NOT EXISTS "IDX_enterprise_license_keys_customer" ON public."enterpriseLicenseKeys" USING btree ("enterpriseCustomerId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_license_keys_license_id" ON public."enterpriseLicenseKeys" USING btree ("licenseId");
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_enterprise_license_keys_license_id_unique" ON public."enterpriseLicenseKeys" USING btree ("licenseId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_license_keys_request" ON public."enterpriseLicenseKeys" USING btree ("licenseRequestId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_license_keys_system_type" ON public."enterpriseLicenseKeys" USING btree ("systemType");
CREATE UNIQUE INDEX IF NOT EXISTS enterprise_license_requests_pkey ON public."enterpriseLicenseRequests" USING btree (id);
CREATE INDEX IF NOT EXISTS "IDX_enterprise_license_requests_customer" ON public."enterpriseLicenseRequests" USING btree ("enterpriseCustomerId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_license_requests_renewal" ON public."enterpriseLicenseRequests" USING btree ("enterpriseCustomerId", "autoApproveRenewals");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_license_requests_status" ON public."enterpriseLicenseRequests" USING btree (status);
CREATE INDEX IF NOT EXISTS "IDX_enterprise_revenue_sync_customer" ON public."enterpriseRevenueSync" USING btree ("enterpriseCustomerId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_revenue_sync_license" ON public."enterpriseRevenueSync" USING btree ("licenseKeyId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_revenue_sync_synced" ON public."enterpriseRevenueSync" USING btree ("syncedAt");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_telemetry_customer" ON public."enterpriseSystemDailyTelemetry" USING btree ("enterpriseCustomerId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_telemetry_customer_report" ON public."enterpriseSystemDailyTelemetry" USING btree ("enterpriseCustomerId", "reportDate");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_telemetry_customer_system_report" ON public."enterpriseSystemDailyTelemetry" USING btree ("enterpriseCustomerId", "enterpriseSystemId", "reportDate");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_telemetry_report_date" ON public."enterpriseSystemDailyTelemetry" USING btree ("reportDate");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_telemetry_system" ON public."enterpriseSystemDailyTelemetry" USING btree ("enterpriseSystemId");
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_enterprise_telemetry_unique_daily" ON public."enterpriseSystemDailyTelemetry" USING btree ("enterpriseCustomerId", "enterpriseSystemId", "organizationId", "reportDate");
CREATE UNIQUE INDEX IF NOT EXISTS enterprise_systems_pkey ON public."enterpriseSystems" USING btree (id);
CREATE INDEX IF NOT EXISTS "IDX_enterprise_systems_customer" ON public."enterpriseSystems" USING btree ("enterpriseCustomerId");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_systems_license_status" ON public."enterpriseSystems" USING btree ("enterpriseCustomerId", "licenseStatus");
CREATE INDEX IF NOT EXISTS "IDX_enterprise_systems_type" ON public."enterpriseSystems" USING btree ("enterpriseCustomerId", "systemType");
CREATE UNIQUE INDEX IF NOT EXISTS organization_domains_domain_unique ON public."organizationDomains" USING btree (domain);
CREATE UNIQUE INDEX IF NOT EXISTS "organizations_inviteCode_unique" ON public.organizations USING btree ("inviteCode");
CREATE UNIQUE INDEX IF NOT EXISTS organizations_pkey ON public.organizations USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformConfiguration_key_unique" ON public."platformConfiguration" USING btree (key);
CREATE UNIQUE INDEX IF NOT EXISTS "platformConfiguration_pkey" ON public."platformConfiguration" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformPricing_pkey" ON public."platformPricing" USING btree (id);
CREATE INDEX IF NOT EXISTS idx_podcast_provider_cost_created ON public."podcastProviderCostLedger" USING btree ("createdAt");
CREATE INDEX IF NOT EXISTS idx_podcast_provider_cost_lesson ON public."podcastProviderCostLedger" USING btree ("lessonId");
CREATE INDEX IF NOT EXISTS idx_podcast_provider_cost_org ON public."podcastProviderCostLedger" USING btree ("organizationId");
CREATE INDEX IF NOT EXISTS idx_podcast_provider_cost_version ON public."podcastProviderCostLedger" USING btree ("versionId");
CREATE UNIQUE INDEX IF NOT EXISTS "podcast_provider_cost_ledger_correlationId_key" ON public."podcastProviderCostLedger" USING btree ("correlationId");
CREATE UNIQUE INDEX IF NOT EXISTS unq_podcast_provider_cost_correlation_runtime ON public."podcastProviderCostLedger" USING btree ("correlationId");
CREATE INDEX IF NOT EXISTS idx_podcast_settlement_created ON public."podcastSettlementLedger" USING btree ("createdAt");
CREATE INDEX IF NOT EXISTS idx_podcast_settlement_lesson ON public."podcastSettlementLedger" USING btree ("lessonId");
CREATE INDEX IF NOT EXISTS idx_podcast_settlement_org ON public."podcastSettlementLedger" USING btree ("organizationId");
CREATE INDEX IF NOT EXISTS idx_podcast_settlement_version ON public."podcastSettlementLedger" USING btree ("versionId");
CREATE UNIQUE INDEX IF NOT EXISTS "podcast_settlement_ledger_correlationId_key" ON public."podcastSettlementLedger" USING btree ("correlationId");
CREATE UNIQUE INDEX IF NOT EXISTS "podcast_settlement_ledger_versionId_key" ON public."podcastSettlementLedger" USING btree ("versionId");
CREATE UNIQUE INDEX IF NOT EXISTS unq_podcast_settlement_correlation_runtime ON public."podcastSettlementLedger" USING btree ("correlationId");
CREATE UNIQUE INDEX IF NOT EXISTS unq_podcast_settlement_version_runtime ON public."podcastSettlementLedger" USING btree ("versionId");
CREATE UNIQUE INDEX IF NOT EXISTS "quizCreditPricing_pkey" ON public."quizCreditPricing" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "UNQ_quiz_pricing_org_tier" ON public."quizCreditPricing" USING btree ("organizationId", "questionTier");
CREATE UNIQUE INDEX IF NOT EXISTS "supportedLanguages_pkey" ON public."supportedLanguages" USING btree (code);
CREATE UNIQUE INDEX IF NOT EXISTS "systemSettings_pkey" ON public."systemSettings" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "systemSettings_settingKey_key" ON public."systemSettings" USING btree ("settingKey");
CREATE UNIQUE INDEX IF NOT EXISTS "systemSettings_settingKey_unique" ON public."systemSettings" USING btree ("settingKey");
CREATE UNIQUE INDEX IF NOT EXISTS "userOrganizationRoles_pkey" ON public."userOrganizationRoles" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON public.users USING btree (email);
CREATE UNIQUE INDEX IF NOT EXISTS "users_gamerName_unique" ON public.users USING btree ("gamerName");
CREATE UNIQUE INDEX IF NOT EXISTS users_pkey ON public.users USING btree (id);
