-- Auto-generated from DEV runtime DB diff since last successful build
-- Scope: cloud
-- Previous schema hash: 89e0d858c4fea4cf5e8e0fb527ee2a1df8d5136c38ab33f40c6173a2aac90e25
-- Current schema hash: f7c32a4f36778dafb33ce6f2e89eb860a5b7393b7aa0bab4ef5c7105625c3988
-- Generated at: 2026-04-13T18:38:19.541Z
DO $$ BEGIN ALTER TABLE IF EXISTS "achievementCatalog" ADD CONSTRAINT "achievementCatalog_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "achievementUnlocks" ADD CONSTRAINT "achievementUnlocks_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "activeOneVOneGames" ADD CONSTRAINT "activeOneVOneGames_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "activePowerUps" ADD CONSTRAINT "activePowerUps_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "activeQuizGames" ADD CONSTRAINT "activeQuizGames_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "adminChallengeConfig" ADD CONSTRAINT "adminChallengeConfig_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "brandingThemes" ADD CONSTRAINT "brandingThemes_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "buildVersions" ADD CONSTRAINT "buildVersions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "bulkQuizGenerationJobs" ADD CONSTRAINT "bulkQuizGenerationJobs_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "businessPackagePrices" ADD CONSTRAINT "businessPackagePrices_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "businessPackages" ADD CONSTRAINT "businessPackages_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "cardCollections" ADD CONSTRAINT "cardCollections_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "cards" ADD CONSTRAINT "cards_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "cardStats" ADD CONSTRAINT "cardStats_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "certificates" ADD CONSTRAINT "certificates_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "challengeProgress" ADD CONSTRAINT "challengeProgress_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "challengeTemplates" ADD CONSTRAINT "challengeTemplates_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "coinAdjustments" ADD CONSTRAINT "coinAdjustments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "coinTransactions" ADD CONSTRAINT "coinTransactions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "collectionStatTypes" ADD CONSTRAINT "collectionStatTypes_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "contentTranslationJobs" ADD CONSTRAINT "contentTranslationJobs_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "cosmeticOwnership" ADD CONSTRAINT "cosmeticOwnership_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseAssignments" ADD CONSTRAINT "courseAssignments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseCategories" ADD CONSTRAINT "courseCategories_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseDraftCoverageReports" ADD CONSTRAINT "courseDraftCoverageReports_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseDraftDocuments" ADD CONSTRAINT "courseDraftDocuments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseDraftDocumentSegments" ADD CONSTRAINT "courseDraftDocumentSegments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseDraftFrameworks" ADD CONSTRAINT "courseDraftFrameworks_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseDrafts" ADD CONSTRAINT "courseDrafts_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseDraftTopicAssignments" ADD CONSTRAINT "courseDraftTopicAssignments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseFrameworks" ADD CONSTRAINT "courseFrameworks_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "coursePayoutLineItems" ADD CONSTRAINT "coursePayoutLineItems_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "coursePayouts" ADD CONSTRAINT "coursePayouts_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "coursePriceHistory" ADD CONSTRAINT "coursePriceHistory_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseProgress" ADD CONSTRAINT "courseProgress_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "coursePurchases" ADD CONSTRAINT "coursePurchases_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseRatings" ADD CONSTRAINT "courseRatings_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseRefunds" ADD CONSTRAINT "courseRefunds_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseReviews" ADD CONSTRAINT "courseReviews_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseTags" ADD CONSTRAINT "courseTags_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseUpgradeOrders" ADD CONSTRAINT "courseUpgradeOrders_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseVersionNotifications" ADD CONSTRAINT "courseVersionNotifications_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseVersions" ADD CONSTRAINT "courseVersions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "courseVersionUpgrades" ADD CONSTRAINT "courseVersionUpgrades_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "creditAllocations" ADD CONSTRAINT "creditAllocations_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "creditOrders" ADD CONSTRAINT "creditOrders_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "creditPurchasePackages" ADD CONSTRAINT "creditPurchasePackages_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "creditTransactions" ADD CONSTRAINT "creditTransactions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "creditUsageLogs" ADD CONSTRAINT "creditUsageLogs_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "dailyStreaks" ADD CONSTRAINT "dailyStreaks_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "drizzleMigrations" ADD CONSTRAINT "drizzleMigrations_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "elearningSubscriptionPlans" ADD CONSTRAINT "elearningSubscriptionPlans_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "emailLogs" ADD CONSTRAINT "emailLogs_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "enterpriseAgreementTemplates" ADD CONSTRAINT "enterpriseAgreementTemplates_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "enterpriseDocuments" ADD CONSTRAINT "enterpriseDocuments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "enterpriseKeyring" ADD CONSTRAINT "enterpriseKeyring_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "enterpriseRevenueSync" ADD CONSTRAINT "enterpriseRevenueSync_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "enterpriseSystemDailyTelemetry" ADD CONSTRAINT "enterpriseSystemDailyTelemetry_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "equippedCosmetics" ADD CONSTRAINT "equippedCosmetics_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "exchangeRateHistory" ADD CONSTRAINT "exchangeRateHistory_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "explanationTerms" ADD CONSTRAINT "explanationTerms_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "financialAuditLog" ADD CONSTRAINT "financialAuditLog_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "gameResults" ADD CONSTRAINT "gameResults_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "gameRooms" ADD CONSTRAINT "gameRooms_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "gamificationEconomyRules" ADD CONSTRAINT "gamificationEconomyRules_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "gammaCreditLedger" ADD CONSTRAINT "gammaCreditLedger_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "gammaImageStyles" ADD CONSTRAINT "gammaImageStyles_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "gammaThemes" ADD CONSTRAINT "gammaThemes_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "guestSessions" ADD CONSTRAINT "guestSessions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "integrationEvents" ADD CONSTRAINT "integrationEvents_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "interOrgCourseAssignmentRules" ADD CONSTRAINT "interOrgCourseAssignmentRules_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "joinRequestApprovalTokens" ADD CONSTRAINT "joinRequestApprovalTokens_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "joinRequests" ADD CONSTRAINT "joinRequests_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "leaderBoard" ADD CONSTRAINT "leaderBoard_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonAccessLogs" ADD CONSTRAINT "lessonAccessLogs_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonAssignments" ADD CONSTRAINT "lessonAssignments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonContentVersions" ADD CONSTRAINT "lessonContentVersions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonFeedbackItems" ADD CONSTRAINT "lessonFeedbackItems_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonFeedbackRuns" ADD CONSTRAINT "lessonFeedbackRuns_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonPresentationVersions" ADD CONSTRAINT "lessonPresentationVersions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonProgress" ADD CONSTRAINT "lessonProgress_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonProgressSlides" ADD CONSTRAINT "lessonProgressSlides_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonQuizLinks" ADD CONSTRAINT "lessonQuizLinks_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessons" ADD CONSTRAINT "lessons_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonScopeAssignments" ADD CONSTRAINT "lessonScopeAssignments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonSlides" ADD CONSTRAINT "lessonSlides_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonTranslationJobs" ADD CONSTRAINT "lessonTranslationJobs_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lessonVersions" ADD CONSTRAINT "lessonVersions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "licenseFlagAudit" ADD CONSTRAINT "licenseFlagAudit_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "licenseFlagOverrides" ADD CONSTRAINT "licenseFlagOverrides_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "licensePayments" ADD CONSTRAINT "licensePayments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "licenseRolloutBetaUsers" ADD CONSTRAINT "licenseRolloutBetaUsers_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "licenseRolloutOrganizations" ADD CONSTRAINT "licenseRolloutOrganizations_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "loginStreaks" ADD CONSTRAINT "loginStreaks_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "lpCreditLedger" ADD CONSTRAINT "lpCreditLedger_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "notificationPreferences" ADD CONSTRAINT "notificationPreferences_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "onpremLicenseState" ADD CONSTRAINT "onpremLicenseState_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationBankDetails" ADD CONSTRAINT "organizationBankDetails_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationBankingDetails" ADD CONSTRAINT "organizationBankingDetails_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationDomains" ADD CONSTRAINT "organizationDomains_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationLicenses" ADD CONSTRAINT "organizationLicenses_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationLicenseSettings" ADD CONSTRAINT "organizationLicenseSettings_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationPackageAssignments" ADD CONSTRAINT "organizationPackageAssignments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationPackageOverrides" ADD CONSTRAINT "organizationPackageOverrides_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationSubUnits" ADD CONSTRAINT "organizationSubUnits_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationTeams" ADD CONSTRAINT "organizationTeams_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationUnits" ADD CONSTRAINT "organizationUnits_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "organizationUsageLimits" ADD CONSTRAINT "organizationUsageLimits_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "orgCreditLedger" ADD CONSTRAINT "orgCreditLedger_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "packageChangeEvents" ADD CONSTRAINT "packageChangeEvents_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "packageRecommendationDismissals" ADD CONSTRAINT "packageRecommendationDismissals_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "paymentFulfillments" ADD CONSTRAINT "paymentFulfillments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "paymentIntents" ADD CONSTRAINT "paymentIntents_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "paymentTransactions" ADD CONSTRAINT "paymentTransactions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "paymentWebhookEvents" ADD CONSTRAINT "paymentWebhookEvents_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "payoutBatches" ADD CONSTRAINT "payoutBatches_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "payoutDisbursements" ADD CONSTRAINT "payoutDisbursements_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "payoutTransactions" ADD CONSTRAINT "payoutTransactions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "pendingGammaJobs" ADD CONSTRAINT "pendingGammaJobs_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformCostAllocations" ADD CONSTRAINT "platformCostAllocations_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformCostCategories" ADD CONSTRAINT "platformCostCategories_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformCostCategoryTypes" ADD CONSTRAINT "platformCostCategoryTypes_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformCostEntries" ADD CONSTRAINT "platformCostEntries_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformFinancialAuditLog" ADD CONSTRAINT "platformFinancialAuditLog_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformFinancialSnapshots" ADD CONSTRAINT "platformFinancialSnapshots_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformPaymentSettings" ADD CONSTRAINT "platformPaymentSettings_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformReportJobs" ADD CONSTRAINT "platformReportJobs_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformReportSchedules" ADD CONSTRAINT "platformReportSchedules_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformRevenueReports" ADD CONSTRAINT "platformRevenueReports_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "platformRevenueSources" ADD CONSTRAINT "platformRevenueSources_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "playerSeasonRewards" ADD CONSTRAINT "playerSeasonRewards_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "playerSessions" ADD CONSTRAINT "playerSessions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "playerStats" ADD CONSTRAINT "playerStats_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "podcastProviderCostLedger" ADD CONSTRAINT "podcastProviderCostLedger_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "podcastSettlementLedger" ADD CONSTRAINT "podcastSettlementLedger_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "postFulfillmentJobs" ADD CONSTRAINT "postFulfillmentJobs_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "powerUpCatalog" ADD CONSTRAINT "powerUpCatalog_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "powerUpInventory" ADD CONSTRAINT "powerUpInventory_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizCardExplanations" ADD CONSTRAINT "quizCardExplanations_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizCards" ADD CONSTRAINT "quizCards_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizCardVersions" ADD CONSTRAINT "quizCardVersions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizCollectionAssignments" ADD CONSTRAINT "quizCollectionAssignments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizCollections" ADD CONSTRAINT "quizCollections_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizCollectionVersions" ADD CONSTRAINT "quizCollectionVersions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizDrafts" ADD CONSTRAINT "quizDrafts_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizGameProgress" ADD CONSTRAINT "quizGameProgress_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "quizGameResults" ADD CONSTRAINT "quizGameResults_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "reviewModerationActions" ADD CONSTRAINT "reviewModerationActions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "salesInquiries" ADD CONSTRAINT "salesInquiries_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "seasonPassConfig" ADD CONSTRAINT "seasonPassConfig_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "seasonPassProgress" ADD CONSTRAINT "seasonPassProgress_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "seasonPassPurchases" ADD CONSTRAINT "seasonPassPurchases_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "seasonPassTiers" ADD CONSTRAINT "seasonPassTiers_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "shopItemPricing" ADD CONSTRAINT "shopItemPricing_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "subjects" ADD CONSTRAINT "subjects_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "subscriptionEvents" ADD CONSTRAINT "subscriptionEvents_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "subscriptionInvoices" ADD CONSTRAINT "subscriptionInvoices_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "subscriptionPlans" ADD CONSTRAINT "subscriptionPlans_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "subscriptions" ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "systemChangeEvents" ADD CONSTRAINT "systemChangeEvents_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "termDefinitions" ADD CONSTRAINT "termDefinitions_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "translationAnalyticsEvents" ADD CONSTRAINT "translationAnalyticsEvents_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "translationAnalyticsEvents" ADD CONSTRAINT "UNQ_translation_analytics_dedupe" UNIQUE ("dedupeKey"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "translationIndexFailures" ADD CONSTRAINT "translationIndexFailures_jobId_translationIndexJobs_id_fk" FOREIGN KEY ("jobId") REFERENCES "translationIndexJobs"(id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "translationIndexFailures" ADD CONSTRAINT "translationIndexFailures_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "translationIndexJobs" ADD CONSTRAINT "translationIndexJobs_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "translationSearchDocuments" ADD CONSTRAINT "translationSearchDocuments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "unitSubjects" ADD CONSTRAINT "unitSubjects_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "universalStatUnits" ADD CONSTRAINT "universalStatUnits_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "userCourseEnrollments" ADD CONSTRAINT "userCourseEnrollments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "userCourseLessonProgress" ADD CONSTRAINT "userCourseLessonProgress_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "userCreditAdjustments" ADD CONSTRAINT "userCreditAdjustments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "userCreditAllocations" ADD CONSTRAINT "userCreditAllocations_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "userLicenses" ADD CONSTRAINT "userLicenses_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "userNotifications" ADD CONSTRAINT "userNotifications_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "userOrganizationAssignments" ADD CONSTRAINT "userOrganizationAssignments_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "userQuizProgress" ADD CONSTRAINT "userQuizProgress_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "webhookEvents" ADD CONSTRAINT "webhookEvents_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE IF EXISTS "webhookRegistrations" ADD CONSTRAINT "webhookRegistrations_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS "achievementCatalog_pkey" ON public."achievementCatalog" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "achievementUnlocks_pkey" ON public."achievementUnlocks" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "activeOneVOneGames_pkey" ON public."activeOneVOneGames" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "activePowerUps_pkey" ON public."activePowerUps" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "activeQuizGames_pkey" ON public."activeQuizGames" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "adminChallengeConfig_pkey" ON public."adminChallengeConfig" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "brandingThemes_pkey" ON public."brandingThemes" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "buildVersions_pkey" ON public."buildVersions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "bulkQuizGenerationJobs_pkey" ON public."bulkQuizGenerationJobs" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "businessPackagePrices_pkey" ON public."businessPackagePrices" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "businessPackages_pkey" ON public."businessPackages" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "cardCollections_pkey" ON public."cardCollections" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS cards_pkey ON public.cards USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "cardStats_pkey" ON public."cardStats" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS certificates_pkey ON public.certificates USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "challengeProgress_pkey" ON public."challengeProgress" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "challengeTemplates_pkey" ON public."challengeTemplates" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "coinAdjustments_pkey" ON public."coinAdjustments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "coinTransactions_pkey" ON public."coinTransactions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "collectionStatTypes_pkey" ON public."collectionStatTypes" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "contentTranslationJobs_pkey" ON public."contentTranslationJobs" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "cosmeticOwnership_pkey" ON public."cosmeticOwnership" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseAssignments_pkey" ON public."courseAssignments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseCategories_pkey" ON public."courseCategories" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseDraftCoverageReports_pkey" ON public."courseDraftCoverageReports" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseDraftDocuments_pkey" ON public."courseDraftDocuments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseDraftDocumentSegments_pkey" ON public."courseDraftDocumentSegments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseDraftFrameworks_pkey" ON public."courseDraftFrameworks" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseDrafts_pkey" ON public."courseDrafts" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseDraftTopicAssignments_pkey" ON public."courseDraftTopicAssignments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseFrameworks_pkey" ON public."courseFrameworks" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "coursePayoutLineItems_pkey" ON public."coursePayoutLineItems" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "coursePayouts_pkey" ON public."coursePayouts" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "coursePriceHistory_pkey" ON public."coursePriceHistory" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseProgress_pkey" ON public."courseProgress" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "coursePurchases_pkey" ON public."coursePurchases" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseRatings_pkey" ON public."courseRatings" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseRefunds_pkey" ON public."courseRefunds" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseReviews_pkey" ON public."courseReviews" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseTags_pkey" ON public."courseTags" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseUpgradeOrders_pkey" ON public."courseUpgradeOrders" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseVersionNotifications_pkey" ON public."courseVersionNotifications" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseVersions_pkey" ON public."courseVersions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "courseVersionUpgrades_pkey" ON public."courseVersionUpgrades" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "creditAllocations_pkey" ON public."creditAllocations" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "creditOrders_pkey" ON public."creditOrders" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "creditPurchasePackages_pkey" ON public."creditPurchasePackages" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "creditTransactions_pkey" ON public."creditTransactions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "creditUsageLogs_pkey" ON public."creditUsageLogs" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "dailyStreaks_pkey" ON public."dailyStreaks" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "drizzleMigrations_pkey" ON public."drizzleMigrations" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "elearningSubscriptionPlans_pkey" ON public."elearningSubscriptionPlans" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "emailLogs_pkey" ON public."emailLogs" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "enterpriseAgreementTemplates_pkey" ON public."enterpriseAgreementTemplates" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "enterpriseDocuments_pkey" ON public."enterpriseDocuments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "enterpriseKeyring_pkey" ON public."enterpriseKeyring" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "enterpriseRevenueSync_pkey" ON public."enterpriseRevenueSync" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "enterpriseSystemDailyTelemetry_pkey" ON public."enterpriseSystemDailyTelemetry" USING btree (id);
CREATE INDEX IF NOT EXISTS "IDX_enterpriseSystems_sync_auth_mode" ON public."enterpriseSystems" USING btree ("enterpriseCustomerId", "syncAuthMode");
CREATE UNIQUE INDEX IF NOT EXISTS "equippedCosmetics_pkey" ON public."equippedCosmetics" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "exchangeRateHistory_pkey" ON public."exchangeRateHistory" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "explanationTerms_pkey" ON public."explanationTerms" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "financialAuditLog_pkey" ON public."financialAuditLog" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "gameResults_pkey" ON public."gameResults" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "gameRooms_pkey" ON public."gameRooms" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "gamificationEconomyRules_pkey" ON public."gamificationEconomyRules" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "gammaCreditLedger_pkey" ON public."gammaCreditLedger" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "gammaImageStyles_pkey" ON public."gammaImageStyles" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "gammaThemes_pkey" ON public."gammaThemes" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "guestSessions_pkey" ON public."guestSessions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "integrationEvents_pkey" ON public."integrationEvents" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "interOrgCourseAssignmentRules_pkey" ON public."interOrgCourseAssignmentRules" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "joinRequestApprovalTokens_pkey" ON public."joinRequestApprovalTokens" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "joinRequests_pkey" ON public."joinRequests" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "leaderBoard_pkey" ON public."leaderBoard" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonAccessLogs_pkey" ON public."lessonAccessLogs" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonAssignments_pkey" ON public."lessonAssignments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonContentVersions_pkey" ON public."lessonContentVersions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonFeedbackItems_pkey" ON public."lessonFeedbackItems" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonFeedbackRuns_pkey" ON public."lessonFeedbackRuns" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonPresentationVersions_pkey" ON public."lessonPresentationVersions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonProgress_pkey" ON public."lessonProgress" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonProgressSlides_pkey" ON public."lessonProgressSlides" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonQuizLinks_pkey" ON public."lessonQuizLinks" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS lessons_pkey ON public.lessons USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonScopeAssignments_pkey" ON public."lessonScopeAssignments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonSlides_pkey" ON public."lessonSlides" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonTranslationJobs_pkey" ON public."lessonTranslationJobs" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lessonVersions_pkey" ON public."lessonVersions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "licenseFlagAudit_pkey" ON public."licenseFlagAudit" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "licenseFlagOverrides_pkey" ON public."licenseFlagOverrides" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "licensePayments_pkey" ON public."licensePayments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "licenseRolloutBetaUsers_pkey" ON public."licenseRolloutBetaUsers" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "licenseRolloutOrganizations_pkey" ON public."licenseRolloutOrganizations" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "loginStreaks_pkey" ON public."loginStreaks" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "lpCreditLedger_pkey" ON public."lpCreditLedger" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "notificationPreferences_pkey" ON public."notificationPreferences" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "onpremLicenseState_pkey" ON public."onpremLicenseState" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationBankDetails_pkey" ON public."organizationBankDetails" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationBankingDetails_pkey" ON public."organizationBankingDetails" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationDomains_pkey" ON public."organizationDomains" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationLicenses_pkey" ON public."organizationLicenses" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationLicenseSettings_pkey" ON public."organizationLicenseSettings" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationPackageAssignments_pkey" ON public."organizationPackageAssignments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationPackageOverrides_pkey" ON public."organizationPackageOverrides" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationSubUnits_pkey" ON public."organizationSubUnits" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationTeams_pkey" ON public."organizationTeams" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationUnits_pkey" ON public."organizationUnits" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "organizationUsageLimits_pkey" ON public."organizationUsageLimits" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "orgCreditLedger_pkey" ON public."orgCreditLedger" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "packageChangeEvents_pkey" ON public."packageChangeEvents" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "packageRecommendationDismissals_pkey" ON public."packageRecommendationDismissals" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "paymentFulfillments_pkey" ON public."paymentFulfillments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "paymentIntents_pkey" ON public."paymentIntents" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "paymentTransactions_pkey" ON public."paymentTransactions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "paymentWebhookEvents_pkey" ON public."paymentWebhookEvents" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "payoutBatches_pkey" ON public."payoutBatches" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "payoutDisbursements_pkey" ON public."payoutDisbursements" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "payoutTransactions_pkey" ON public."payoutTransactions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "pendingGammaJobs_pkey" ON public."pendingGammaJobs" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformCostAllocations_pkey" ON public."platformCostAllocations" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformCostCategories_pkey" ON public."platformCostCategories" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformCostCategoryTypes_pkey" ON public."platformCostCategoryTypes" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformCostEntries_pkey" ON public."platformCostEntries" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformFinancialAuditLog_pkey" ON public."platformFinancialAuditLog" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformFinancialSnapshots_pkey" ON public."platformFinancialSnapshots" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformPaymentSettings_pkey" ON public."platformPaymentSettings" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformReportJobs_pkey" ON public."platformReportJobs" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformReportSchedules_pkey" ON public."platformReportSchedules" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformRevenueReports_pkey" ON public."platformRevenueReports" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "platformRevenueSources_pkey" ON public."platformRevenueSources" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "playerSeasonRewards_pkey" ON public."playerSeasonRewards" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "playerSessions_pkey" ON public."playerSessions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "playerStats_pkey" ON public."playerStats" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "podcastProviderCostLedger_pkey" ON public."podcastProviderCostLedger" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "podcastSettlementLedger_pkey" ON public."podcastSettlementLedger" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "postFulfillmentJobs_pkey" ON public."postFulfillmentJobs" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "powerUpCatalog_pkey" ON public."powerUpCatalog" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "powerUpInventory_pkey" ON public."powerUpInventory" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "quizCardExplanations_pkey" ON public."quizCardExplanations" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "quizCards_pkey" ON public."quizCards" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "quizCardVersions_pkey" ON public."quizCardVersions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "quizCollectionAssignments_pkey" ON public."quizCollectionAssignments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "quizCollections_pkey" ON public."quizCollections" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "quizCollectionVersions_pkey" ON public."quizCollectionVersions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "quizDrafts_pkey" ON public."quizDrafts" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "quizGameProgress_pkey" ON public."quizGameProgress" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "quizGameResults_pkey" ON public."quizGameResults" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "reviewModerationActions_pkey" ON public."reviewModerationActions" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "salesInquiries_pkey" ON public."salesInquiries" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "seasonPassConfig_pkey" ON public."seasonPassConfig" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "seasonPassProgress_pkey" ON public."seasonPassProgress" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "seasonPassPurchases_pkey" ON public."seasonPassPurchases" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "seasonPassTiers_pkey" ON public."seasonPassTiers" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "shopItemPricing_pkey" ON public."shopItemPricing" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS subjects_pkey ON public.subjects USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "subscriptionEvents_pkey" ON public."subscriptionEvents" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "subscriptionInvoices_pkey" ON public."subscriptionInvoices" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "subscriptionPlans_pkey" ON public."subscriptionPlans" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_pkey ON public.subscriptions USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "systemChangeEvents_pkey" ON public."systemChangeEvents" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "termDefinitions_pkey" ON public."termDefinitions" USING btree (id);
CREATE INDEX IF NOT EXISTS "IDX_translation_analytics_event" ON public."translationAnalyticsEvents" USING btree ("eventType");
CREATE INDEX IF NOT EXISTS "IDX_translation_analytics_lang" ON public."translationAnalyticsEvents" USING btree ("languageCode");
CREATE INDEX IF NOT EXISTS "IDX_translation_analytics_occurred" ON public."translationAnalyticsEvents" USING btree ("occurredAt");
CREATE INDEX IF NOT EXISTS "IDX_translation_analytics_org" ON public."translationAnalyticsEvents" USING btree ("organizationId");
CREATE INDEX IF NOT EXISTS "IDX_translation_analytics_variant" ON public."translationAnalyticsEvents" USING btree ("variantId");
CREATE UNIQUE INDEX IF NOT EXISTS "translationAnalyticsEvents_pkey" ON public."translationAnalyticsEvents" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "UNQ_translation_analytics_dedupe" ON public."translationAnalyticsEvents" USING btree ("dedupeKey");
CREATE INDEX IF NOT EXISTS "IDX_translation_index_failures_deadletter" ON public."translationIndexFailures" USING btree ("deadLettered");
CREATE INDEX IF NOT EXISTS "IDX_translation_index_failures_job" ON public."translationIndexFailures" USING btree ("jobId");
CREATE INDEX IF NOT EXISTS "IDX_translation_index_failures_org" ON public."translationIndexFailures" USING btree ("organizationId");
CREATE UNIQUE INDEX IF NOT EXISTS "translationIndexFailures_pkey" ON public."translationIndexFailures" USING btree (id);
CREATE INDEX IF NOT EXISTS "IDX_translation_index_jobs_entity" ON public."translationIndexJobs" USING btree ("entityType", "entityId");
CREATE INDEX IF NOT EXISTS "IDX_translation_index_jobs_next_retry" ON public."translationIndexJobs" USING btree ("nextRetryAt");
CREATE INDEX IF NOT EXISTS "IDX_translation_index_jobs_org" ON public."translationIndexJobs" USING btree ("organizationId");
CREATE INDEX IF NOT EXISTS "IDX_translation_index_jobs_status" ON public."translationIndexJobs" USING btree (status);
CREATE UNIQUE INDEX IF NOT EXISTS "translationIndexJobs_pkey" ON public."translationIndexJobs" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "UNQ_translation_index_jobs_dedupe" ON public."translationIndexJobs" USING btree ("dedupeKey");
CREATE INDEX IF NOT EXISTS "IDX_translation_search_docs_entity" ON public."translationSearchDocuments" USING btree ("entityType", "entityId");
CREATE INDEX IF NOT EXISTS "IDX_translation_search_docs_group_lang" ON public."translationSearchDocuments" USING btree ("contentGroupId", "languageCode");
CREATE INDEX IF NOT EXISTS "IDX_translation_search_docs_org" ON public."translationSearchDocuments" USING btree ("organizationId");
CREATE UNIQUE INDEX IF NOT EXISTS "translationSearchDocuments_pkey" ON public."translationSearchDocuments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "UNQ_translation_search_docs_entity_lang" ON public."translationSearchDocuments" USING btree ("entityType", "entityId", "languageCode");
CREATE UNIQUE INDEX IF NOT EXISTS "unitSubjects_pkey" ON public."unitSubjects" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "universalStatUnits_pkey" ON public."universalStatUnits" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "userCourseEnrollments_pkey" ON public."userCourseEnrollments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "userCourseLessonProgress_pkey" ON public."userCourseLessonProgress" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "userCreditAdjustments_pkey" ON public."userCreditAdjustments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "userCreditAllocations_pkey" ON public."userCreditAllocations" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "userLicenses_pkey" ON public."userLicenses" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "userNotifications_pkey" ON public."userNotifications" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "userOrganizationAssignments_pkey" ON public."userOrganizationAssignments" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "userQuizProgress_pkey" ON public."userQuizProgress" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "webhookEvents_pkey" ON public."webhookEvents" USING btree (id);
CREATE UNIQUE INDEX IF NOT EXISTS "webhookRegistrations_pkey" ON public."webhookRegistrations" USING btree (id);
